server.port: 3000

management.endpoints.web.exposure.include: "*"

#mybatis entity scan packages
#mybatis.type-aliases-package: "de.schmidtdennis.mysqlspring"
#Mapper.xml location
mybatis.mapper-locations: "classpath*:de/schmidtdennis/mysqlspring/mapper/*.xml"

spring:
  redis:
    host: "redis"
    port: 6379
    password: "secretredis"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


logging:
  config: file:logback-spring.xml

springdoc:
  swagger-ui:
    path: /swagger-ui


keycloak:
  realm: popupchinese
  auth-server-url: http://keycloak:8080/auth #using "keycloak" container name.
  ssl-required: external
  resource: popupchineseapp
  bearer-only: true
  public-client: true
  principal-attribute: preferred_username
