server.port: 3000

management.endpoints.web.exposure.include: "*"

#mybatis entity scan packages
#mybatis.type-aliases-package: "de.schmidtdennis.mysqlspring"
#Mapper.xml location
mybatis.mapper-locations: "classpath*:de/schmidtdennis/mysqlspring/mapper/*.xml"

spring:
  redis:
    host: "redis"
    port: 6379
    password: "secretredis"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


logging:
  config: file:logback-spring.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
