management.endpoints.web.exposure.include: "*"

#mybatis entity scan packages
#mybatis.type-aliases-package: "de.schmidtdennis.mysqlspring"
#Mapper.xml location
mybatis.mapper-locations: "classpath*:de/schmidtdennis/mysqlspring/mapper/*.xml"

spring:
  redis:
    host: "redis"
    port: 6379


logging:
  config: file:logback-spring.xml
